CREATE DATABASE QUANLYNHANVIEN
GO

USE QUANLYNHANVIEN
GO

--- NHÂN VIÊN
CREATE TABLE NHANVIEN(
	MANV VARCHAR(10),
	HO NVARCHAR(20) NOT NULL,
	TENLOT NVARCHAR(20) NOT NULL,
	TEN NVARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH IN(N'Nam', N'Nữ')),
	DIACHI NVARCHAR(100),
	SODIENTHOAI VARCHAR(11),
	MAIL VARCHAR(50),
	MAQL VARCHAR(10),
	MAPB VARCHAR(10),
	MACV VARCHAR(10),
	MATD VARCHAR(10),

	PRIMARY KEY (MANV)
)

--- PHÒNG BAN
CREATE TABLE PHONGBAN(
	MAPB VARCHAR(10),
	TENPHONGBAN NVARCHAR(50) UNIQUE,
	TRUONGPHONG VARCHAR(10) UNIQUE,
	DIACHI NVARCHAR(100),

	PRIMARY KEY (MAPB)
)

--- ĐỀ ÁN
CREATE TABLE DEAN(
	MADA VARCHAR(10),
	TENDEAN NVARCHAR(50) NOT NULL,
	MAPB VARCHAR(10),

	PRIMARY KEY (MADA)
)

--- NHÂN VIÊN VÀ ĐỀ ÁN
CREATE TABLE NHANVIEN_DEAN(
	MADA VARCHAR(10),
	MANV VARCHAR(10),
	THOIGIAN INT CHECK(THOIGIAN > 0),

	PRIMARY KEY(MADA, MANV)
)

--- CHỨC VỤ
CREATE TABLE CHUCVU(
	MACV VARCHAR(10),
	TENCHUCVU NVARCHAR(50) UNIQUE,

	PRIMARY KEY (MACV)
)

--- LƯƠNG
CREATE TABLE LUONG(
	BACLUONG INT,
	LUONGCOBAN MONEY NOT NULL CHECK(LUONGCOBAN > 0),
	LUONGPHUCAP MONEY CHECK(LUONGPHUCAP > 0),
	HESOLUONG FLOAT NOT NULL CHECK(HESOLUONG > 0),

	PRIMARY KEY (BACLUONG)
)

--- NHÂN VIÊN VÀ LƯƠNG
CREATE TABLE NHANVIEN_LUONG(
	MANV VARCHAR(10),
	BACLUONG INT,
	LUONGTHUONG MONEY CHECK(LUONGTHUONG > 0),
	LUONGPHAT MONEY CHECK(LUONGPHAT > 0), 

	PRIMARY KEY (MANV, BACLUONG)
)

--- TRÌNH ĐỘ
CREATE TABLE TRINHDO(
	MATD VARCHAR(10),
	TENTRINHDO NVARCHAR(50) UNIQUE,

	PRIMARY KEY (MATD)
)

--- HỢP ĐỒNG
CREATE TABLE HOPDONG(
	MAHD VARCHAR(10),
	LOAIHOPDONG NVARCHAR(30) UNIQUE,

	PRIMARY KEY (MAHD)
)

--- BẢO HIỂM
CREATE TABLE BAOHIEM(
	MABH VARCHAR(10),
	TENBAOHIEM NVARCHAR(20) UNIQUE,
	CHIPHI MONEY NOT NULL CHECK(CHIPHI > 0),

	PRIMARY KEY (MABH)
)

--- NHÂN VIÊN VÀ BẢO HIỂM
CREATE TABLE NHANVIEN_BAOHIEM(
	MABH VARCHAR(10),
	MANV VARCHAR(10),

	PRIMARY KEY(MABH, MANV)
)

--- THÂN NHÂN 
CREATE TABLE THANNHAN(
	MANV VARCHAR(10),
	TENTHANNHAN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH IN(N'Nam', N'Nữ')),
	MOIQUANHE NVARCHAR(10) NOT NULL,

	PRIMARY KEY(MANV, TENTHANNHAN)
)

--- TABLE NHANVIEN ----------------------------------------------
ALTER TABLE NHANVIEN ADD FOREIGN KEY(MAQL) REFERENCES NHANVIEN(MANV)
ALTER TABLE NHANVIEN ADD FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB)
ALTER TABLE NHANVIEN ADD FOREIGN KEY(MACV) REFERENCES CHUCVU(MACV)
ALTER TABLE NHANVIEN ADD FOREIGN KEY(MACV) REFERENCES TRINHDO(MATD)

--- TABLE PHONGBAN ----------------------------------------------
ALTER TABLE PHONGBAN ADD FOREIGN KEY(TRUONGPHONG) REFERENCES NHANVIEN(MANV)

--- TABLE NHANVIEN_DEAN -----------------------------------------
ALTER TABLE NHANVIEN_DEAN ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE NHANVIEN_DEAN ADD FOREIGN KEY(MADA) REFERENCES DEAN(MADA)

--- TABLE NHANVIEN_LUONG -----------------------------------------
ALTER TABLE NHANVIEN_LUONG ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE NHANVIEN_LUONG ADD FOREIGN KEY(BACLUONG) REFERENCES LUONG(BACLUONG)

--- TABLE NHANVIEN_BAOHIEM -----------------------------------------
ALTER TABLE NHANVIEN_BAOHIEM ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
ALTER TABLE NHANVIEN_BAOHIEM ADD FOREIGN KEY(MABH) REFERENCES BAOHIEM(MABH)

--- TABLE THANNHAN -----------------------------------------
ALTER TABLE THANNHAN ADD FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)


--- TABLE BAOHIEM -----------------------------------------
INSERT INTO BAOHIEM
	(MABH, TENBAOHIEM, CHIPHI)
VALUES
	('BHYT', N'Bảo hiểm y tế', 300000),
	('BHTNLDBNN', N'Bảo hiểm tai nạn lao động, bệnh nghề nghiệp', 400000),
	('BHXH', N'Bảo hiểm xã hội', 500000),
	('BHTN', N'Bảo hiểm thất nghiệm', 600000);