CREATE DATABASE QUANLYNHANVIEN
GO

CREATE TABLE PHONGBAN(
	MAPB VARCHAR(10) PRIMARY KEY,
	TENPHONGBAN NVARCHAR(50) NOT NULL,
	TRUONGPHONG VARCHAR(10) UNIQUE
)

CREATE TABLE CHUCVU(
	MACV VARCHAR(10) PRIMARY KEY,
	TENCHUCVU NVARCHAR(50) UNIQUE
)

CREATE TABLE LUONG(
	BACLUONG INT PRIMARY KEY,
	LUONGCOBAN MONEY NOT NULL,
	LUONGPHUCAP MONEY,
	HESOLUONG FLOAT NOT NULL
)

CREATE TABLE TRINHDO(
	MATD VARCHAR(10) PRIMARY KEY,
	TENTRINHDO NVARCHAR(50) NOT NULL,
)

CREATE TABLE TRINHDONHANVIEN(
	MATD VARCHAR(10),
	MANV VARCHAR(10),
	KINHNGHIEM INT NOT NULL CHECK (KINHNGHIEM >=0)

	PRIMARY KEY (MATD, MANV, KINHNGHIEM)
)

CREATE TABLE CHUNGCHI(
	MANV VARCHAR(10),
	MATD VARCHAR(10),
	CHUNGCHI NVARCHAR(50)

	PRIMARY KEY(MANV, MATD, CHUNGCHI)
)

CREATE TABLE HOPDONGLAODONG(
	MAHD VARCHAR(10) PRIMARY KEY,
	LOAIHOPDONG NVARCHAR(30),
	NGAYBATDAU DATE,
	NGAYKETTHUC DATE
)

CREATE TABLE BAOHIEM(
	MABH VARCHAR(10) PRIMARY KEY,
	TENBAOHIEM NVARCHAR(20),
	CHIPHI MONEY
)

CREATE TABLE THANNHAN(
	MANV VARCHAR(10),
	TENTHANNHAN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH IN(N'Nam', N'Nữ')),
	MOIQUANHE NVARCHAR(10)

	PRIMARY KEY(MANV, TENTHANNHAN)
)

CREATE TABLE NHANVIEN(
	MANV VARCHAR(10) PRIMARY KEY,
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	GIOITINH NVARCHAR(3) CHECK (GIOITINH IN(N'Nam', N'Nữ')),
	DANTOC NVARCHAR(20),
	QUEQUAN NVARCHAR(20),
	QUOCTICH NVARCHAR(20),
	SODIENTHOAI VARCHAR(11),
	MAIL VARCHAR(50),
	NGUOIQUANLY VARCHAR(10),
	MAPB VARCHAR(10),
	MACV VARCHAR(10),
	BACLUONG INT,
	MATD VARCHAR(10),
	MAHD VARCHAR(10),

	FOREIGN KEY(NGUOIQUANLY) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(MAPB) REFERENCES PHONGBAN(MAPB),
	FOREIGN KEY(MACV) REFERENCES CHUCVU(MACV),
	FOREIGN KEY(BACLUONG) REFERENCES LUONG(BACLUONG),
	FOREIGN KEY(MATD) REFERENCES TRINHDO(MATD),
	FOREIGN KEY(MAHD) REFERENCES HOPDONGLAODONG(MAHD)
)

CREATE TABLE THAMGIA(
	MABH VARCHAR(10),
	MANV VARCHAR(10),
	THOIGIAN INT

	PRIMARY KEY(MABH, MANV, THOIGIAN)

	FOREIGN KEY(MABH) REFERENCES BAOHIEM(MABH),
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE DEAN(
	MADA VARCHAR(10) PRIMARY KEY,
	TENDEAN NVARCHAR(50)
)

CREATE TABLE PHANCONG(
	MADA VARCHAR(10),
	MANV VARCHAR(10),
	THOIGIAN INT

	PRIMARY KEY(MADA, MANV, THOIGIAN)

	FOREIGN KEY(MADA) REFERENCES DEAN(MADA),
	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)
)

CREATE TABLE LUONGTHUONGPHAT(
	BACLUONG INT,
	MANV VARCHAR(10),
	LUONGTHUONG MONEY,
	LUONGPHAT MONEY

	FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	FOREIGN KEY(BACLUONG) REFERENCES LUONG(BACLUONG)
)

ALTER TABLE PHONGBAN FOREIGN KEY(TRUONGPHONG) REFERENCES NHANVIEN(MANV)
ALTER TABLE TRINHDONHANVIEN FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV)



